cabal-version: 3.0
name: t0mb-net
version: 0.1.0.0
build-type: Simple

executable site
  main-is: site.hs
  hs-source-dirs: ., src
  other-modules: Cinema, CinemaRendering, Publishing, View
  build-depends:
      base >= 4.14 && < 5
    , hakyll
    , filepath
    , scientific, aeson
    , bytestring
    , containers
    , crypton
    , directory
    , text
    , time
    , unicode-transforms
    , yaml
    , tagsoup
  default-language: Haskell2010
  ghc-options: -Wall -threaded
